floating ip assign script implemented

diff --git a/hetzner-failover/templates/configmap-script.yaml b/hetzner-failover/templates/configmap-script.yaml
--- a/hetzner-failover/templates/configmap-script.yaml
+++ b/hetzner-failover/templates/configmap-script.yaml
@@ -5,17 +5,16 @@ metadata:
 data:
   notify.sh: |
     #!/bin/bash
+    echo "running script..."
     ENDSTATE=$3
     NAME=$2
     TYPE=$1
     if [ "$ENDSTATE" == "MASTER" ] ; then
         HOST_IP=$(ip route get 8.8.8.8 | awk '{print $7 }')
-        echo "setting Failover IP:  $FAILOVER_IP to Server IP:  $HOST_IP"
-
-        export SERVER_ID=$(curl -H "Authorization: Bearer YOURTOKEN" "https://api.hetzner.cloud/v1/servers?name=$HOSTNAME" | jq '.servers[0].id')
-        export FLOATING_IP_ID=$(curl -H "Authorization: Bearer YOURTOKEN" "https://api.hetzner.cloud/v1/floating_ips" | jq '.floating_ips[] | select(.description=="keepalived")' | jq '.id')
-        export FLOATING_IP=$(curl -H "Authorization: Bearer YOURTOKEN" "https://api.hetzner.cloud/v1/floating_ips" | jq '.floating_ips[] | select(.description=="keepalived")' | jq -r '.ip')
-        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer YOURTOKEN" -d "{\"server\":$SERVER_ID}" "https://api.hetzner.cloud/v1/floating_ips/$FLOATING_IP_ID/actions/assign" # added by exocode
-        curl -k -u "$HETZNER_USER:$HETZNER_PASS" https://robot-ws.your-server.de/failover/$FAILOVER_IP -d active_server_ip=$HOST_IP
-
+        export SERVER_ID=$(curl -H "Authorization: Bearer $HETZNER_TOKEN" "https://api.hetzner.cloud/v1/servers?name=$HOSTNAME" |python3 -c "import sys, json; print(json.load(sys.stdin)['servers'][0]['id'])")
+        export FLOATING_IP_ID=$(curl -H "Authorization: Bearer $HETZNER_TOKEN" "https://api.hetzner.cloud/v1/floating_ips" |python3 -c "import json,sys;fips=json.load(sys.stdin)['floating_ips'];[print(ip['id']) for ip in fips if ip['description'] == 'fip1.global-nights.com']")
+        export FLOATING_IP=$(curl -H "Authorization: Bearer $HETZNER_TOKEN" "https://api.hetzner.cloud/v1/floating_ips" |python3 -c "import json,sys;fips=json.load(sys.stdin)['floating_ips'];[print(ip['ip']) for ip in fips if ip['description'] == 'fip1.global-nights.com']")
+        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $HETZNER_TOKEN" -d "{\"server\":$SERVER_ID}" "https://api.hetzner.cloud/v1/floating_ips/$FLOATING_IP_ID/actions/assign"
+        ip addr add $FLOATING_IP/32 dev eth0 || echo "IP was already added to the interface"
+        echo "setting Failover IP:  $FLOATING_IP to Server IP:  $HOST_IP"
     fi
